openapi: 3.0.3
info:
  title: GovIO API
  x-summary: GovIO Communications
  x-api-id: govio-backoffice
  version: 1.0.1
tags:
  - name: file
  - name: message
  - name: service
  - name: template
  
servers:
  - url: 'http://localhost:10001'
    description: Sample Deployment URL (Not Actual)
security:
  - header-principal: []
paths:

  /organizations:
    get:
      tags:
        - organization
      summary: Retrieve the organization list.
      description: Retrieve the organization list.
      operationId: listOrganizations
      parameters:
        - $ref: 'govhub-api-commons.yaml#/components/parameters/limit'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/offset'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/q_query'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/organization_ordering_query'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/sort_direction_query'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/with_roles'
        - $ref: '#/components/parameters/with_service_instance'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: 'govhub-api-commons.yaml#/components/schemas/OrganizationList'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  /files:
    post:
      tags:
        - file
      summary: Upload a new csv trace.
      description: Allows to upload a csv trace for a GovIO service.
      operationId: uploadFile
      parameters:
         - $ref: '#/components/parameters/service_instance_id_query_optional'
#   TODO: Ristabilire la versione con service_instance_id_query e rimuovere dagli schema l' _optional
         - $ref: "#/components/parameters/service_id_query_optional"
         - $ref: "#/components/parameters/organization_id_query_optional"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: text/csv
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioFile'
          links:
             self:
                $ref: "#/components/links/readFile"
             content:
                $ref: "#/components/links/readFileContent"
             messages:
                $ref: "#/components/links/readFileMessages"
             
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
    get:
      tags:
        - file
      summary: Retrieve the uploaded csv traces
      description: Retrieve the csv traces
      operationId: listFiles
      parameters:
        - $ref: 'govhub-api-commons.yaml#/components/parameters/limit'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/offset'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/q_query'
        - $ref: '#/components/parameters/user_id_query_optional'
        - $ref: '#/components/parameters/service_id_query_optional'
        - $ref: '#/components/parameters/organization_id_query_optional'
        - $ref: '#/components/parameters/creation_date_from'
        - $ref: '#/components/parameters/creation_date_to'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/sort_direction_query'
        - $ref: '#/components/parameters/file_ordering_query'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileList'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  '/files/{id}':
    parameters:
      - $ref: '#/components/parameters/file_id'
    get:
      tags:
        - file
      summary: Retrieve the uploaded csv trace.
      description: Retrieve the csv trace.
      operationId: readFile
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioFile'
          links:
             content:
                $ref: "#/components/links/readFileContent"
             messages:
                $ref: "#/components/links/readFileMessages"                
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  '/files/{id}/content':
    parameters:
      - $ref: '#/components/parameters/file_id'
    get:
      tags:
        - file
      summary: Retrieve the file content of the uploaded csv trace.
      description: Retrieve the file content
      operationId: readFileContent
      responses:
        '200':
          description: Successful operation.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  '/files/{id}/file_messages':
    parameters:
      - $ref: '#/components/parameters/file_id'
    get:
      tags:
        - file
      parameters:
        - $ref: 'govhub-api-commons.yaml#/components/parameters/limit'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/offset'
        - $ref: '#/components/parameters/file_message_status_query'
        - $ref: '#/components/parameters/line_number_from_query'
      summary: Retrieve the file processing messages.
      description: Retrieve the file messages.
      operationId: readFileMessages
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMessageList'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  /messages:
    post:
      tags:
        - message
      parameters:
        - $ref: '#/components/parameters/service_instance_id_query'
      summary: Send a new message.
      description: Send a message through the service template.
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GovioNewMessage'
        required: true
      responses:
        '201':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioMessage'
          links:
            self:
              $ref: "#/components/links/readMessage"
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
    get:
      tags:
        - message
      parameters:
        - $ref: '#/components/parameters/scheduled_expedition_date_from_query'
        - $ref: '#/components/parameters/scheduled_expedition_date_to_query'
        - $ref: '#/components/parameters/expedition_date_from_query'
        - $ref: '#/components/parameters/expedition_date_to_query'
        - $ref: '#/components/parameters/tax_code_query'
        - $ref: '#/components/parameters/service_id_query_optional'
        - $ref: '#/components/parameters/organization_id_query_optional'
        - $ref: '#/components/parameters/message_ordering_query'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/sort_direction_query'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/limit'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/offset'
      summary: List Govio Messages
      description: Read and Filter the Govio Messages.
      operationId: listMessages
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioMessageList'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  '/messages/{id}':
    parameters:
      - $ref: '#/components/parameters/message_id'
    get:
      tags:
        - message
      summary: Reads a Govio Message
      description: Read the message with the provided id.
      operationId: readMessage
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioMessage'               
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  /service-instances:
    get:
      tags:
        - service
      parameters:
        - $ref: '#/components/parameters/service_id_query_optional'
        - $ref: '#/components/parameters/organization_id_query_optional'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/limit'
        - $ref: 'govhub-api-commons.yaml#/components/parameters/offset'
      summary: List Govio Service Instances
      description: Read and Filter the Govio Service Instanes
      operationId: listServiceInstances
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioServiceInstanceList'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  '/service-instances/{id}':
    parameters:
      - $ref: '#/components/parameters/service_instance_id'
    get:
      tags:
        - service
      summary: Retrieve a service instance.
      description: Returns the specified service instance.
      operationId: readServiceInstance
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GovioServiceInstance'
        '400':
          $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
        '401':
          $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
        '403':
          $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
        '404':
          $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'
        '429':
          $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
        '503':
          $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
        default:
          $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
          
  /templates:
     post:
         tags:
           - template
         summary: Create a new template.
         description: Create a new template for sending messages to the govio services.
         operationId: createTemplate
         requestBody:
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/GovioNewTemplate'
           required: true
         responses:
           '201':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioTemplate'
             links:
               self:
                  $ref: "#/components/links/readTemplate"
               assignPlaceholder:
                  $ref: "#/components/links/assignPlaceholder"
               listTemplatePlaceholders:
                  $ref: "#/components/links/listTemplatePlaceholders"
                                  
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'        

     get:
         parameters:
          - $ref: "govhub-api-commons.yaml#/components/parameters/limit"
          - $ref: "govhub-api-commons.yaml#/components/parameters/offset"
          - $ref: "govhub-api-commons.yaml#/components/parameters/q_query"
          - $ref: "govhub-api-commons.yaml#/components/parameters/sort_direction_query"          
         tags:
           - template
         summary: List the templates.
         description: List the  templates used for sending messages to the govio services,sorted by name.
         operationId: listTemplates
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioTemplateList'
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'  

  /templates/{id}:
     parameters:
        - $ref: "#/components/parameters/template_id"
     get:
         tags:
           - template
         summary: Reads a message template.
         description:  Reads a message template.
         operationId: readTemplate
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioTemplate'
             links:
               assignPlaceholder:
                  $ref: "#/components/links/assignPlaceholder"
               listTemplatePlaceholders:
                  $ref: "#/components/links/listTemplatePlaceholders"                   
                   
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '404':
             $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'             
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
   

  /templates/{id}/placeholders:
     parameters:
        - $ref: "#/components/parameters/template_id"
     post:
         parameters:
          - $ref: "#/components/parameters/placeholder_id_query"
         tags:
           - template
         summary: Create a new template placeholder.
         description: Associate a placeholder to a template.
         operationId: assignPlaceholder
         requestBody:
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/GovioNewTemplatePlaceholder'
           required: true
         responses:
           '201':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioTemplatePlaceholder'
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '404':
             $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'             
           '409':
             $ref: 'govhub-api-commons.yaml#/components/responses/409Conflict'
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'
             
     get:
         parameters:
          - $ref: "#/components/parameters/embeds_template_placeholder"
         tags:
           - template
         summary: List the template placeholders.
         description: List the template associated placeholders.
         operationId: listTemplatePlaceholders
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioListTemplatePlaceholder'
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '404':
             $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'             
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'                     

  /placeholders:
     post:
         tags:
           - template
         summary: Create a new template placeholder.
         description: Placeholders can be reused across templates, this endpoints allows to create one.
         operationId: createPlaceholder
         requestBody:
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/GovioNewPlaceholder'
           required: true
         responses:
           '201':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioPlaceholder'
             links:
                self:
                   $ref: "#/components/links/readPlaceholder"
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '409':
             $ref: 'govhub-api-commons.yaml#/components/responses/409Conflict'
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'   

     get:
         parameters:
             - $ref: "govhub-api-commons.yaml#/components/parameters/limit"
             - $ref: "govhub-api-commons.yaml#/components/parameters/offset"
         tags:
           - template
         summary: List the placeholders.
         description: Placeholders can be reused across templates, this endpoints allows to list them.
         operationId: listPlaceholders
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioPlaceholderList'
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault' 
             
             
  /placeholders/{id}:
     parameters:
        - $ref: "#/components/parameters/placeholder_id"
     get:
         tags:
           - template
         summary: Read the specified placeholder.
         description: Placeholders can be reused across templates, this endpoints allows to read one of them.
         operationId: readPlaceholder
         responses:
           '200':
             description: Successful operation.
             content:
               application/json:
                 schema:
                   $ref: '#/components/schemas/GovioPlaceholder'
           '400':
             $ref: 'govhub-api-commons.yaml#/components/responses/400BadRequest'
           '401':
             $ref: 'govhub-api-commons.yaml#/components/responses/401Unauthorized'
           '403':
             $ref: 'govhub-api-commons.yaml#/components/responses/403Forbidden'
           '404':
             $ref: 'govhub-api-commons.yaml#/components/responses/404NotFound'             
           '429':
             $ref: 'govhub-api-commons.yaml#/components/responses/429TooManyRequests'
           '503':
             $ref: 'govhub-api-commons.yaml#/components/responses/503ServiceUnavailable'
           default:
             $ref: 'govhub-api-commons.yaml#/components/responses/ResponseDefault'      
                
components:

  securitySchemes:
    header-principal:
      type: apiKey
      in: header
      name: GovHub-Consumer-Principal
      
  links:
  
    readFile:
       description: Retrieve the file.
       operationId: readFile
       parameters:
         id: $response.body#/id
         
    readFileContent:
       description: Download the file.
       operationId: readFileContent
       parameters:
         id: $response.body#/id
         
    readFileMessages:
       description: Read the file messages
       operationId: readFileMessages
       parameters:
         id: $response.body#/id
         
    readMessage:
        operationId: readMessage
        parameters:
          id: '$response.body#/id'
        description: >
          The `id` value returned in the response can be used as
          the `userId` parameter in `GET /users/{userId}`.
          
    readTemplate:
        operationId: readTemplate
        parameters:
          id: '$response.body#/id'
        description: >
          The `id` value returned in the response can be used as
          the `templateId` parameter for reading the template
          
    assignPlaceholder:
        operationId: assignPlaceholder
        parameters:
          id: '$response.body#/id'
        description: >
          You can assign a new placeholder using The `id` value returned as
          the `templateId` query parameter
          
    listTemplatePlaceholders:
        operationId: listTemplatePlacehodlers
        parameters:
          id: '$response.body#/id'
        description: >
          You can list the placeholder template using the `id` value returned in the response
          for the `templateId`  parameter          
                              
    readPlaceholder:
        operationId: readPlaceholder
        parameters:
          id: '$response.body#/id'
        description: >
          The `id` value returned in the response can be used as
          the `placeholderId` parameter                              
                 
      
  parameters:
  
    embeds_template_placeholder:
       name: embed
       in: query
       required: false
       schema:
          type: array
          minLength:  0
          maxLength: 1024
          items:
             $ref: "#/components/schemas/EmbedPlaceholderEnum"
  
    creation_date_from:
      name: creation_date_from
      in: query
      required: false
      schema:
        type: string
        format: date-time
        
    creation_date_to:
      name: creation_date_to
      in: query
      required: false
      schema:
        type: string
        format: date-time
          
    file_id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GovioFileId'
        
    organization_id_query:
      name: organization_id
      in: query
      required: true
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/OrganizationId'
        
    organization_id_query_optional:
      name: organization_id
      in: query
      required: false
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/OrganizationId'
        
    service_id_query:
      name: service_id
      in: query
      required: true
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/ServiceId'
        
    service_id_query_optional:
      name: service_id
      in: query
      required: false
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/ServiceId'
        
    template_id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GovioTemplateId'      
                
    placeholder_id_query:
      name: placeholder_id
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/GovioPlaceholderId'
        
    placeholder_id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GovioPlaceholderId'
                
    user_id_query_optional:
      name: user_id
      in: query
      required: false
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/UserId'
  
        
    file_message_status_query:
      name: file_message_status
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/FileMessageStatusEnum'
        
    line_number_from_query:
      name: line_number_from
      in: query
      required: false
      schema:
        type: integer
        format: int64
        minimum: 0
        maximum: 99999999
        
    message_id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/MessageId'
        
    service_instance_id_query:
      name: service_instance
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/GovioServiceInstanceId'
        
    service_instance_id_query_optional:
      name: service_instance
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/GovioServiceInstanceId'
        
    service_instance_id:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GovioServiceInstanceId'
        
    tax_code_query:
      name: tax_code
      in: query
      required: false
      schema:
        $ref: 'govhub-api-commons.yaml#/components/schemas/TaxCode'
        
    expedition_date_to_query:
      name: expedition_date_to
      in: query
      required: false
      schema:
        type: string
        format: date-time
        
    expedition_date_from_query:
      name: expedition_date_from
      in: query
      required: false
      schema:
        type: string
        format: date-time
        
    scheduled_expedition_date_to_query:
      name: scheduled_expedition_date_to
      in: query
      required: false
      schema:
        type: string
        format: date-time
        
    scheduled_expedition_date_from_query:
      name: scheduled_expedition_date_from
      in: query
      required: false
      schema:
        type: string
        format: date-time
        
    with_service_instance:
      name: with_service_instance
      in: query
      required: false
      schema:
        type: boolean
        
    message_ordering_query:
         name: sort
         in: query
         description: Sorting field.
         required: true
         schema:
            $ref: "#/components/schemas/MessageOrdering"        
            
    file_ordering_query:
         name: sort
         in: query
         description: Sorting field.
         required: true
         schema:
            $ref: "#/components/schemas/FileOrdering"            
        
        
  schemas:
  

    GovioBaseMessage:
      required:
        - markdown
        - scheduled_expedition_date
        - taxcode
      type: object
      properties:
        taxcode:
          type: string
          maxLength: 16
          minLength: 16
          description: 'The fiscal code of the user, all upper case.'
          pattern: >-
            [A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]
        payment:
          $ref: '#/components/schemas/GovioMessagePaymentItem'
        email:
           $ref: "govhub-api-commons.yaml#/components/schemas/Email"
        scheduled_expedition_date:
          type: string
          format: date-time
        due_date:
          type: string
          format: date-time
          
    GovioFile:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/GovioFileId'
        filename:
          type: string
          pattern: .*
          maxLength: 256
          example: file1.csv
        user:
          $ref: '#/components/schemas/FileUserItem'
        organization:
          $ref: 'govhub-api-commons.yaml#/components/schemas/OrganizationAuthItem'
        service:
          $ref: 'govhub-api-commons.yaml#/components/schemas/ServiceAuthItem'
        status:
          $ref: '#/components/schemas/FileStatus'
        creation_date:
          type: string
          format: date-time
        processing_date:
          type: string
          format: date-time
        error_messages:
          type: integer
          format: int64
          minimum: 0
          maximum: 9223372036854776000
          example: 9999
        acquired_messages:
          type: integer
          format: int64
          minimum: 0
          maximum: 9223372036854776000
          example: 9999
        _links:
           type: object
           additionalProperties: false
           properties:
              self:
                 $ref: "govhub-api-commons.yaml#/components/schemas/Link"
              content:
                 $ref: "govhub-api-commons.yaml#/components/schemas/Link"
           example:
              self: 
                 href: "https://govhub.it/govio/files/1"                
              content: 
                 href: "https://govhub.it/govio/files/1/content"
      required:
        - creation_date
        - status
        - user
        - service
        - organization
        - id          
            
    GovioMessage:
      allOf:
        - $ref: '#/components/schemas/GovioBaseMessage'
        - type: object
          required:
            - id
            - status
            - creation_date
            - markdown
            - subject
          properties:
            id:
              type: integer
              description: GovIO Message Id.
              format: int64
              example: 1
            status:
              $ref: '#/components/schemas/GovioMessageStatus'
            status_detail:
              maxLength: 2000000
              minLength: 0
              pattern: .*
              type: string
            appio_message_id:
              maxLength: 1024
              minLength: 0
              pattern: .*
              type: string
            creation_date:
              type: string
              format: date-time
            expedition_date:
              type: string
              format: date-time
            last_update_status:
              type: string
              format: date-time
            subject:
              minLength: 10
              maxLength: 120
              type: string
              example: Lorem ipsum
            markdown:
              minLength: 80
              maxLength: 10000
              type: string
              example: >-
                # Lorem ipsum dolor sit amet

                Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat.            
            _links:
               type: object
               additionalProperties: false
               properties:
                  self:
                     $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                  service_instance:
                     $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                  sender:
                     $ref: "govhub-api-commons.yaml#/components/schemas/Link"
               example:
                  self:
                     href: "https://govhub.it/govio/messages/1"
                  service_instance:
                     href: "https://govhub.it/govio/service-instances/1"
                  sender:
                     href: "https://govhub.it/govio/users/1"
                
    GovioMessagePaymentItem:
      type: object
      required:
        - amount
        - notice_number
      properties:
        amount:
          description: >-
            Amount of payment in euro cent. PagoPA accepts up to 9999999999 euro
            cents.
          type: integer
          format: int64
          minimum: 1
          maximum: 9999999999
        notice_number:
          description: Payment ID in pagoPA
          type: string
          pattern: '^[0123][0-9]{17}$'
        invalid_after_due_date:
          type: boolean
        payee_taxcode:
          maxLength: 11
          minLength: 11
          pattern: '[0-9]{11}'
          type: string
                              
    GovioNewMessage:
      allOf:
        - $ref: '#/components/schemas/GovioBaseMessage'
        - type: object
          properties:
            placeholders:
              type: array
              items:
                 $ref: "#/components/schemas/Placeholder"
              minItems: 0
              maxItems: 2147483647                 
                 
    GovioNewPlaceholder:
       type: object
       additionalProperties: false
       required:
          - name
          - example
          - type
       properties:
          name:
             type: string
             pattern: .*
             maxLength:  9223372036854776000
             example: cie
          description:
             type: string
             pattern: .*
             maxLength:  9223372036854776000
             example: Numero carta d'identità elettronica.
          example:
             type: string
             pattern: .*
             maxLength:  9223372036854776000
             example: CA000000AA
          pattern:
             type: string
             pattern: .*
             maxLength:  9223372036854776000
             example:  "[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]" 
          type:
             $ref: "#/components/schemas/GovioPlaceholderType"

    GovioNewTemplatePlaceholder:
       type: object
       additionalProperties: false
       required:
          - mandatory
          - position
       properties:
          mandatory:
             type: boolean
          position:
             type: integer
             format: int32
             minimum: 0
             maximum:  2147483647
             
    GovioNewTemplate:
       type: object
       additionalProperties: false
       required: 
          - subject
          - message_body
          - has_payment
          - has_due_date
       properties:
          name:
             type: string
             pattern: .*
             maxLength: 9223372036854776000
             example: Spedizione Messaggio CIE
          description:
             type: string
             pattern: .*
             maxLength: 9223372036854776000
             example: Segnala la scadenza della proprià C.I.E. 
          subject:
             type: string
             pattern: .*
             maxLength: 9223372036854776000
             example: Scadenza CIE n. ${cie.uppercase}
          message_body:
             type: string
             pattern: .*
             maxLength: 9223372036854776000
             example: Salve, con la presente la informiamo che in data ${due_date} scadrà la Carta di Identità elettronica numero ${cie.uppercase}.             
          has_payment:
             type: boolean
          has_due_date:
             type: boolean

    GovioPlaceholder:
       allOf:
          - $ref: "#/components/schemas/GovioNewPlaceholder"
          - type: object
            additionalProperties: false
            required:
              - id            
            properties:
               id:
                  $ref: "#/components/schemas/GovioPlaceholderId"
               _links:
                  type: object
                  additionalProperties: false
                  properties:
                     self:
                        $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                  example:
                     self:
                        href: "https://govhub.it/govio/placeholders/1"
                  
    GovioPlaceholderList:
         allOf:
            - $ref: "govhub-api-commons.yaml#/components/schemas/List"
            - type: object
              properties:              
                 items:
                    type: array
                    items:
                       $ref: "#/components/schemas/GovioPlaceholder"
                    minItems: 0
                    maxItems: 2147483647
              required:
                 - items 
              additionalProperties: false                      

    GovioTemplate:
       allOf:
          - $ref: '#/components/schemas/GovioNewTemplate'
          - type: object
            properties:
                id:
                   $ref: '#/components/schemas/GovioTemplateId'
                _links:
                   type: object
                   additionalProperties: false
                   properties:
                      self:
                         $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                      placeholders:
                         $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                   example:
                      self:
                         href: "https://govhub.it/govio/templates/1"
                      placeholders:
                         href: "https://govhub.it/govio/templates/1/placeholders"
                                          
    GovioTemplateList:
         allOf:
            - $ref: "govhub-api-commons.yaml#/components/schemas/List"
            - type: object
              properties:              
                 items:
                    type: array
                    items:
                       $ref: "#/components/schemas/GovioTemplate"
                    minItems: 0
                    maxItems: 2147483647
              required:
                 - items 
              additionalProperties: false                                          
                                          
    GovioTemplatePlaceholder:
       allOf:
          - $ref: "#/components/schemas/GovioNewTemplatePlaceholder"
          - type: object
            additionalProperties: false            
            properties:
                _links:
                   type: object
                   properties:
                      placeholder:
                         $ref: "govhub-api-commons.yaml#/components/schemas/Link"
                   example:
                      placeholder:
                         href: "https://govhub.it/govio/placeholders/1"
                      template:
                         href: "https://govhub.it/govio/templates/1"
                _embedded:
                   type: object
                   properties:
                      placeholder:
                         $ref: "#/components/schemas/GovioPlaceholder"
                      template:
                         $ref: "#/components/schemas/GovioTemplate"
                    
    GovioListTemplatePlaceholder:
       type: object
       additionalProperties: false
       properties:
          items:
             type: array
             minItems: 0
             maxItems: 2147483647
             items:
                $ref: "#/components/schemas/GovioTemplatePlaceholder"
                           
    GovioFileId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: Govio File Id.
    
    GovioServiceInstanceId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: Govio Service Instance Id.
    
    FileMessageId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: GovIO File Message Id.
    
    MessageId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: GovIO Message Id.
     
    GovioTemplateId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: GovIO Template Id.    


    GovioPlaceholderId:
      type: integer
      format: int64
      minimum: 0
      example: 1
      description: GovIO Placeholder Id.    
    
    EmbedPlaceholderEnum:
       type: string
       enum:
           - placeholder
           - template
      
    FileStatus:
      type: string
      enum:
        - created
        - processing
        - processed
        
    FileMessageStatusEnum:
      type: string
      enum:
        - acquired
        - error
        - any
      default: any
      
    GovioPlaceholderType:
       type: string
       enum:
          - string
          - date
          - datetime
      
    GovioMessageStatus:
      type: string
      enum:
        - accepted
        - throttled
        - scheduled
        - recipient_allowed
        - profile_not_exists
        - sender_not_allowed
        - denied
        - sent
        - bad_request
        - forbidden
        - processed
        - created
        
    FileUserItem:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: 'govhub-api-commons.yaml#/components/schemas/UserId'
        full_name:
          type: string
          maxLength: 255
          pattern: ^.*$
          example: Antonio Giscardi
      required:
        - id
        - full_name
        
    GovioServiceInstance:
      type: object
      additionalProperties: false
      properties:
        service:
          $ref: 'govhub-api-commons.yaml#/components/schemas/ServiceAuthItem'
        organization:
          $ref: 'govhub-api-commons.yaml#/components/schemas/OrganizationAuthItem'
        _links:
           type: object
           additionalProperties: false
           properties:
              self:
                 $ref: "govhub-api-commons.yaml#/components/schemas/Link"
           example:
              self:
                 href: "https://govhub.it/govio/service-instances/1"
          
    FileList:
      allOf:
        - $ref: 'govhub-api-commons.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/GovioFile'
              minItems: 0
              maxItems: 2147483647
          required:
            - items
          additionalProperties: false
          
          
    GovioServiceInstanceList:
      allOf:
        - $ref: 'govhub-api-commons.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/GovioServiceInstance'
              minItems: 0
              maxItems: 2147483647
          required:
            - items
          additionalProperties: false
          
    GovioMessageList:
      allOf:
        - $ref: 'govhub-api-commons.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/GovioMessage'
              minItems: 0
              maxItems: 2147483647
          required:
            - items
          additionalProperties: false
          
    FileMessageList:
      allOf:
        - $ref: 'govhub-api-commons.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/FileMessage'
              minItems: 0
              maxItems: 2147483647
          required:
            - items
          additionalProperties: false
          
    FileMessage:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/FileMessageId'
        line_number:
          type: integer
          format: int64
          minimum: 0
          maximum: 9223372036854776000
          example: 1
        line_record:
          type: string
          pattern: .*
          maxLength: 20000000
        message:
          $ref: '#/components/schemas/GovioMessageItem'
        status:
          $ref: '#/components/schemas/FileMessageStatusEnum'
      required:
        - id
        - status
        
    GovioMessageItem:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/MessageId'
      required:
        - id
        
    MessageOrdering:
         type: string
         enum:
            - unsorted
            - scheduled_expedition_date
            - id
         default: id        
         
    FileOrdering:
         type: string
         enum:
            - unsorted
            - creation_date
            - id
         default: id
         
    Placeholder:
       type: object
       required:
         - name
         - value
       properties:
         name:
           type: string
           pattern: .*
           maxLength: 2000000
         value:
           type: string
           pattern: .*
           maxLength: 2000000    
             
